In [1]:
import tensorflow as tf
from tensorflow import keras

from PIL import Image
import numpy as np
# Load pre-trained CNN model
model = keras.models.load_model('sbirCNN.h5')


In [2]:
class_mapping = {}
class_names = ['aircraft carrier', 'airplane', 'alarm clock', 'ambulance', 'angel', 'animal migration', 'ant', 'anvil', 'apple', 'arm', 'asparagus', 'axe', 'backpack', 'banana', 'bandage', 'barn', 'baseball bat', 'baseball', 'basket', 'basketball', 'bat', 'bathtub', 'beach', 'bear', 'beard', 'bed', 'bee', 'belt', 'bench', 'bicycle', 'binoculars', 'bird', 'birthday cake', 'blackberry', 'blueberry', 'book', 'boomerang', 'bottlecap', 'bowtie', 'bracelet', 'brain', 'bread', 'bridge', 'broccoli', 'broom', 'bucket', 'bulldozer', 'bus', 'bush', 'butterfly', 'cactus', 'cake', 'calculator', 'calendar', 'camel', 'camera', 'camouflage', 'campfire', 'candle', 'cannon', 'canoe', 'car', 'carrot', 'castle', 'cat', 'ceiling fan', 'cell phone', 'cello', 'chair', 'chandelier', 'church', 'circle', 'clarinet', 'clock', 'cloud', 'coffee cup', 'compass', 'computer', 'cookie', 'cooler', 'couch', 'cow', 'crab', 'crayon', 'crocodile', 'crown', 'cruise ship', 'cup', 'diamond', 'dishwasher', 'diving board', 'dog', 'dolphin', 'donut', 'door', 'dragon', 'dresser', 'drill', 'drums', 'duck', 'dumbbell', 'ear', 'elbow', 'elephant', 'envelope', 'eraser', 'eye', 'eyeglasses', 'face', 'fan', 'feather', 'fence', 'finger', 'fire hydrant', 'fireplace', 'firetruck', 'fish', 'flamingo', 'flashlight', 'flip flops', 'floor lamp', 'flower', 'flying saucer', 'foot', 'fork', 'frog', 'frying pan', 'garden hose', 'garden', 'giraffe', 'goatee', 'golf club', 'grapes', 'grass', 'guitar', 'hamburger', 'hammer', 'hand', 'harp', 'hat', 'headphones', 'hedgehog', 'helicopter', 'helmet', 'hexagon', 'hockey puck', 'hockey stick', 'horse', 'hospital', 'hot air balloon', 'hot dog', 'hot tub', 'hourglass', 'house plant', 'house', 'hurricane', 'ice cream', 'jacket', 'jail', 'kangaroo', 'key', 'keyboard', 'knee', 'knife', 'ladder', 'lantern', 'laptop', 'leaf', 'leg', 'light bulb', 'lighter', 'lighthouse', 'lightning', 'line', 'lion', 'lipstick', 'lobster', 'lollipop', 'mailbox', 'map', 'marker', 'matches', 'megaphone', 'mermaid', 'microphone', 'microwave', 'monkey', 'moon', 'mosquito', 'motorbike', 'mountain', 'mouse', 'moustache', 'mouth', 'mug', 'mushroom', 'nail', 'necklace', 'nose', 'ocean', 'octagon', 'octopus', 'onion', 'oven', 'owl', 'paint can', 'paintbrush', 'palm tree', 'panda', 'pants', 'paper clip', 'parachute', 'parrot', 'passport', 'peanut', 'pear', 'peas', 'pencil', 'penguin', 'piano', 'pickup truck', 'picture frame', 'pig', 'pillow', 'pineapple', 'pizza', 'pliers', 'police car', 'pond', 'pool', 'popsicle', 'postcard', 'potato', 'power outlet', 'purse', 'rabbit', 'raccoon', 'radio', 'rain', 'rainbow', 'rake', 'remote control', 'rhinoceros', 'rifle', 'river', 'roller coaster', 'rollerskates', 'sailboat', 'sandwich', 'saw', 'saxophone', 'school bus', 'scissors', 'scorpion', 'screwdriver', 'sea turtle', 'see saw', 'shark', 'sheep', 'shoe', 'shorts', 'shovel', 'sink', 'skateboard', 'skull', 'skyscraper', 'sleeping bag', 'smiley face', 'snail', 'snake', 'snorkel', 'snowflake', 'snowman', 'soccer ball', 'sock', 'speedboat', 'spider', 'spoon', 'spreadsheet', 'square', 'squiggle', 'squirrel', 'stairs', 'star', 'steak', 'stereo', 'stethoscope', 'stitches', 'stop sign', 'stove', 'strawberry', 'streetlight', 'string bean', 'submarine', 'suitcase', 'sun', 'swan', 'sweater', 'swing set', 'sword', 'syringe', 't-shirt', 'table', 'teapot', 'teddy-bear', 'telephone', 'television', 'tennis racquet', 'tent', 'The Eiffel Tower', 'The Great Wall of China', 'The Mona Lisa', 'tiger', 'toaster', 'toe', 'toilet', 'tooth', 'toothbrush', 'toothpaste', 'tornado', 'tractor', 'traffic light', 'train', 'tree', 'triangle', 'trombone', 'truck', 'trumpet', 'umbrella', 'underwear', 'van', 'vase', 'violin', 'washing machine', 'watermelon', 'waterslide', 'whale', 'wheel', 'windmill', 'wine bottle', 'wine glass', 'wristwatch', 'yoga', 'zebra', 'zigzag']

for i, class_name in enumerate(class_names):
    class_mapping[class_name] = i

print(class_mapping)

class_to_label = {}
for label, class_num in class_mapping.items():
    class_to_label[class_num] = f"{label}"

print(class_to_label)

{'aircraft carrier': 0, 'airplane': 1, 'alarm clock': 2, 'ambulance': 3, 'angel': 4, 'animal migration': 5, 'ant': 6, 'anvil': 7, 'apple': 8, 'arm': 9, 'asparagus': 10, 'axe': 11, 'backpack': 12, 'banana': 13, 'bandage': 14, 'barn': 15, 'baseball bat': 16, 'baseball': 17, 'basket': 18, 'basketball': 19, 'bat': 20, 'bathtub': 21, 'beach': 22, 'bear': 23, 'beard': 24, 'bed': 25, 'bee': 26, 'belt': 27, 'bench': 28, 'bicycle': 29, 'binoculars': 30, 'bird': 31, 'birthday cake': 32, 'blackberry': 33, 'blueberry': 34, 'book': 35, 'boomerang': 36, 'bottlecap': 37, 'bowtie': 38, 'bracelet': 39, 'brain': 40, 'bread': 41, 'bridge': 42, 'broccoli': 43, 'broom': 44, 'bucket': 45, 'bulldozer': 46, 'bus': 47, 'bush': 48, 'butterfly': 49, 'cactus': 50, 'cake': 51, 'calculator': 52, 'calendar': 53, 'camel': 54, 'camera': 55, 'camouflage': 56, 'campfire': 57, 'candle': 58, 'cannon': 59, 'canoe': 60, 'car': 61, 'carrot': 62, 'castle': 63, 'cat': 64, 'ceiling fan': 65, 'cell phone': 66, 'cello': 67, 'chai

In [32]:
from PIL import Image
from PIL import ImageOps
from tensorflow.keras.preprocessing.image import  img_to_array
img = Image.open('clock.png')
img = img.resize((28, 28)).convert('L')
img_array = np.array(img)
img_array = np.reshape(img_array, (28, 28, 1))
img_array = img_array / 255.0
print(np.reshape(img_array, (28, 28)), '\n')
#prediction = model.predict(np.array([img_array]))
img1 = tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  3]
  [ 31]
  [ 63]
  [ 95]
  [115]
  [ 86]
  [ 50]
  [  2]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 75]
  [183]
  [176]
  [152]
  [ 10]
  [ 54]
  [182]
  [222]
  [250]
  [255]
  [255]
  [255]
  [255]
  [255]
  [255]
  [231]
  [151]
  [ 61]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [129]
  [255]
  [216]
  [202]
  [255]
  [ 98]
  [220]
  [222]
  [157]
  [125]
  [ 93]
  [ 60]
  [ 28]
  [  8]
  [ 38]
  [ 82]
  [162]
  [239]
  [254]
  [108]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [ 33]
  [250]
  [158]
  [  4]
  [  0]
  [204]
  [209]
  [255]
  [236]
  [105]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  6]
  [164]
  [254]
  [ 88]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [158]
  [243]
  [ 30]
  [155]
  [235]
  [211]
  [255]
  [254]
  [185]
  [255]
  [ 97]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  3]
  [193]
  [229]
  [ 10]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [ 38]
  [251]
  [134]
  [153]
  [251]
  [162]
  [252]
  [245]
  [225]
  [  1]
  [180]
  [241]
  [  6]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 69]
  [255]
  [ 62]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [150]
  [240]
  [ 26]
  [245]
  [145]
  [  0]
  [116]
  [255]
  [149]
  [  0]
  [ 75]
  [255]
  [ 58]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 29]
  [255]
  [ 94]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [209]
  [173]
  [ 77]
  [255]
  [ 62]
  [  0]
  [ 62]
  [255]
  [ 68]
  [  0]
  [ 14]
  [251]
  [122]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  2]
  [249]
  [128]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [240]
  [138]
  [151]
  [236]
  [  4]
  [  0]
  [ 76]
  [255]
  [ 46]
  [  0]
  [  0]
  [221]
  [157]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [218]
  [160]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [251]
  [127]
  [188]
  [188]
  [  0]
  [  0]
  [ 76]
  [255]
  [ 46]
  [  0]
  [  0]
  [213]
  [164]
  [  0]
  [  4]
  [ 45]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [186]
  [193]
  [  0]
  [  0]]

 [[  0]
  [  5]
  [255]
  [117]
  [199]
  [176]
  [  0]
  [  0]
  [ 76]
  [255]
  [ 46]
  [  0]
  [  0]
  [205]
  [173]
  [  0]
  [ 75]
  [251]
  [  9]
  [  0]
  [ 44]
  [154]
  [  2]
  [  0]
  [158]
  [226]
  [  0]
  [  0]]

 [[  0]
  [ 14]
  [255]
  [108]
  [209]
  [166]
  [  0]
  [  0]
  [ 76]
  [255]
  [ 46]
  [  0]
  [  0]
  [160]
  [243]
  [102]
  [ 44]
  [ 61]
  [ 34]
  [ 35]
  [ 98]
  [199]
  [132]
  [170]
  [251]
  [252]
  [  6]
  [  0]]

 [[  0]
  [ 23]
  [255]
  [ 99]
  [220]
  [156]
  [  0]
  [  0]
  [ 76]
  [255]
  [ 46]
  [  0]
  [  0]
  [120]
  [249]
  [255]
  [255]
  [255]
  [255]
  [255]
  [255]
  [255]
  [247]
  [214]
  [202]
  [255]
  [ 24]
  [  0]]

 [[  0]
  [ 17]
  [255]
  [108]
  [221]
  [162]
  [  0]
  [  0]
  [ 72]
  [255]
  [ 51]
  [  0]
  [  0]
  [129]
  [247]
  [ 31]
  [ 82]
  [ 85]
  [ 85]
  [ 85]
  [ 62]
  [ 28]
  [  1]
  [  0]
  [108]
  [255]
  [ 13]
  [  0]]

 [[  0]
  [  0]
  [237]
  [143]
  [159]
  [232]
  [  3]
  [  0]
  [ 38]
  [255]
  [ 87]
  [  0]
  [  0]
  [129]
  [247]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [121]
  [253]
  [  2]
  [  0]]

 [[  0]
  [  0]
  [198]
  [199]
  [ 73]
  [255]
  [ 78]
  [  0]
  [  4]
  [248]
  [127]
  [  0]
  [  0]
  [129]
  [247]
  [  0]
  [  0]
  [  0]
  [ 20]
  [ 63]
  [ 39]
  [  8]
  [  0]
  [  0]
  [134]
  [242]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [ 96]
  [255]
  [101]
  [220]
  [233]
  [ 96]
  [  1]
  [213]
  [166]
  [  0]
  [  0]
  [129]
  [247]
  [  0]
  [ 95]
  [204]
  [253]
  [255]
  [255]
  [255]
  [230]
  [199]
  [218]
  [232]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  1]
  [180]
  [252]
  [136]
  [189]
  [255]
  [106]
  [173]
  [207]
  [  0]
  [  0]
  [129]
  [247]
  [  0]
  [239]
  [228]
  [116]
  [ 63]
  [ 84]
  [115]
  [147]
  [185]
  [255]
  [231]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  8]
  [161]
  [255]
  [163]
  [ 76]
  [ 22]
  [133]
  [246]
  [  2]
  [  0]
  [129]
  [247]
  [  0]
  [198]
  [177]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 49]
  [255]
  [220]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [113]
  [251]
  [242]
  [196]
  [240]
  [255]
  [ 37]
  [  0]
  [129]
  [247]
  [  0]
  [208]
  [168]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [130]
  [254]
  [190]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 56]
  [141]
  [184]
  [165]
  [248]
  [159]
  [  0]
  [126]
  [250]
  [  0]
  [174]
  [224]
  [ 13]
  [  0]
  [  0]
  [  0]
  [  0]
  [219]
  [255]
  [115]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [127]
  [254]
  [ 60]
  [116]
  [255]
  [  5]
  [ 69]
  [252]
  [230]
  [ 96]
  [  2]
  [  0]
  [ 46]
  [255]
  [253]
  [ 30]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  9]
  [215]
  [241]
  [161]
  [255]
  [ 15]
  [  0]
  [ 46]
  [190]
  [255]
  [206]
  [169]
  [244]
  [255]
  [117]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 23]
  [203]
  [255]
  [255]
  [229]
  [217]
  [204]
  [191]
  [227]
  [255]
  [255]
  [251]
  [156]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  1]
  [108]
  [255]
  [183]
  [159]
  [170]
  [185]
  [170]
  [112]
  [ 65]
  [  4]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  3]
  [ 97]
  [ 23]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]], shape=(28, 28, 1), dtype=uint8)
 
print(img1)
prediction = model.predict(img1)
predicted_class_index = np.argmax(prediction, axis=1)[0]

# Map the predicted class index to the label
predicted_label = class_to_label[predicted_class_index]

print(predicted_label)


[[1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.    

TypeError: 'int' object is not subscriptable

In [18]:
def preprocess_sketch(sketchImageData, modelInputWidth, modelInputHeight):
    tensor = tf.image.resize(
        tf.image.convert_image_dtype(sketchImageData, dtype=tf.float32),
        [modelInputHeight, modelInputWidth]
    )
    tensor = tf.math.reduce_mean(tensor, axis=2, keepdims=True)
    tensor = tensor / 255
    tensor = tf.reshape(tensor, [1,modelInputHeight, modelInputWidth, 1])
    return tensor

In [19]:
from PIL import Image
from PIL import ImageOps
from tensorflow.keras.preprocessing.image import  img_to_array,array_to_img
img = Image.open('ladder.png')
# Convert image to numpy array
x = img_to_array(img)
x = preprocess_sketch(x,28,28)
print(x)
#img2 = array_to_img(x)
#print(array_to_img(x))
#print(img2)
#display(img2)
# Get prediction from 250 classes
preds = model.predict(x)
#classes = np.argmax(preds, axis=1)
#print(preds)
# Get the predicted class index
predicted_class_index = np.argmax(preds, axis=1)[0]

# Map the predicted class index to the label
predicted_label = class_to_label[predicted_class_index]

print(predicted_label)

tf.Tensor(
[[[[1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]]

  [[1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]]

  [[1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.        ]
   [1.   